# config/_default/menus.en.toml

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Resume"
  pageRef = "resume"
  weight = 20

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"
